// Unit tests for the SQLite <-> Postgres translation layer.
//
// The live Postgres round-trip cannot run here (no database password, and no local Postgres),
// so everything that CAN be checked without a server is checked here: placeholder rewriting,
// dialect SQL generation, and the portability of the SQL the application actually issues.
process.env.NODE_ENV = 'test';
process.env.DB_PATH = ':memory:';
delete process.env.DATABASE_URL;

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const { toPositional } = require('../server/database');
const { ddl, SCHEMA_VERSION } = require('../server/schema');

test('placeholders are rewritten to $n in order', () => {
  assert.equal(toPositional('SELECT * FROM t WHERE a = ? AND b = ?'), 'SELECT * FROM t WHERE a = $1 AND b = $2');
  assert.equal(toPositional('INSERT INTO t VALUES (?,?,?)'), 'INSERT INTO t VALUES ($1,$2,$3)');
  assert.equal(toPositional('SELECT 1'), 'SELECT 1');
});

test('question marks inside string literals are left alone', () => {
  // A literal '?' is data, not a parameter - rewriting it would corrupt the query.
  assert.equal(
    toPositional("SELECT * FROM t WHERE note = 'why?' AND id = ?"),
    "SELECT * FROM t WHERE note = 'why?' AND id = $1"
  );
  assert.equal(
    toPositional("SELECT 'it''s a ?' AS x WHERE id = ?"),
    "SELECT 'it''s a ?' AS x WHERE id = $1"
  );
  assert.equal(
    toPositional('SELECT "weird?column" FROM t WHERE id = ?'),
    'SELECT "weird?column" FROM t WHERE id = $1'
  );
  assert.equal(
    toPositional('SELECT 1 -- is this ok?\nWHERE id = ?'),
    'SELECT 1 -- is this ok?\nWHERE id = $1'
  );
});

test('dialect helpers produce valid engine-specific SQL', () => {
  const sqlite = require('../server/db'); // no DATABASE_URL -> sqlite
  assert.equal(sqlite.dialect, 'sqlite');
  assert.match(sqlite.sql.greatest('0', 'x'), /^MAX\(/);
  assert.match(sqlite.sql.epochDiff('a', 'b'), /julianday/);

  // Build a Postgres-flavoured handle without connecting, to check the generated SQL.
  const pgSql = {
    epochDiff: (later, earlier) => `EXTRACT(EPOCH FROM (${later}::timestamptz - ${earlier}::timestamptz))`,
    greatest: (a, b) => `GREATEST(${a}, ${b})`,
  };
  assert.match(pgSql.greatest('0', 'x'), /^GREATEST\(/);
  assert.match(pgSql.epochDiff('a', 'b'), /EXTRACT\(EPOCH FROM/);
});

test('schema DDL differs only where the engines require it', () => {
  const lite = ddl('sqlite');
  const pg = ddl('postgres');

  assert.match(lite, /INTEGER PRIMARY KEY AUTOINCREMENT/);
  assert.match(pg, /GENERATED BY DEFAULT AS IDENTITY/);
  assert.equal(/AUTOINCREMENT/.test(pg), false, 'AUTOINCREMENT is SQLite-only');

  assert.match(lite, /COLLATE NOCASE/);
  assert.equal(/COLLATE NOCASE/.test(pg), false, 'COLLATE NOCASE is SQLite-only');
  assert.match(pg, /idx_users_email_lower/, 'Postgres gets a lower(email) unique index instead');

  assert.equal(/\bREAL\b/.test(pg), false, 'REAL is SQLite-only');
  assert.match(pg, /DOUBLE PRECISION/);

  // Both must define the same tables, with the same CHECK constraints.
  for (const table of ['users', 'recipients', 'donations', 'deliveries', 'donation_events', 'notifications']) {
    assert.match(lite, new RegExp(`CREATE TABLE IF NOT EXISTS ${table}\\b`), `sqlite missing ${table}`);
    assert.match(pg, new RegExp(`CREATE TABLE IF NOT EXISTS ${table}\\b`), `postgres missing ${table}`);
  }
  for (const s of ['AVAILABLE', 'MATCHED', 'DRIVER_ASSIGNED', 'PICKED_UP', 'DELIVERED', 'EXPIRED', 'CANCELLED']) {
    assert.ok(lite.includes(`'${s}'`) && pg.includes(`'${s}'`), `status ${s} missing from one dialect`);
  }
  assert.equal(SCHEMA_VERSION, 3);
});

test('no application query uses SQLite-only syntax', () => {
  // These constructs silently break on Postgres, so they must never appear outside the
  // dialect-aware modules (database.js, schema.js and the SQLite-only migration steps).
  const banned = [
    [/\bjulianday\s*\(/i, 'julianday() - use db.sql.epochDiff()'],
    [/\bSUM\s*\(\s*\w+\s*(=|IN)\s/i, 'SUM(boolean) - use SUM(CASE WHEN ... THEN 1 ELSE 0 END)'],
    [/\.prepare\s*\(/, '.prepare() - the sync SQLite API'],
    [/lastInsertRowid/, 'lastInsertRowid - use db.insert()'],
  ];
  const skip = new Set(['database.js', 'schema.js', 'migrate.js']);
  const dirs = [path.join(__dirname, '..', 'server'), path.join(__dirname, '..', 'server', 'routes')];

  const problems = [];
  for (const dir of dirs) {
    for (const name of fs.readdirSync(dir)) {
      if (!name.endsWith('.js') || skip.has(name)) continue;
      const file = path.join(dir, name);
      if (fs.statSync(file).isDirectory()) continue;
      const text = fs.readFileSync(file, 'utf8');
      for (const [re, why] of banned) {
        if (re.test(text)) problems.push(`${name}: ${why}`);
      }
    }
  }
  assert.deepEqual(problems, [], 'portability violations found');
});

test('every INSERT that needs its new id uses db.insert()', () => {
  // db.insert() appends RETURNING id on Postgres; a plain run() would return undefined there.
  for (const f of ['server/profile.js', 'server/routes/donations.js', 'server/seed.js']) {
    const text = fs.readFileSync(path.join(__dirname, '..', f), 'utf8');
    if (/INSERT INTO (users|donations)\b/.test(text)) {
      assert.match(text, /db\.insert\(/, `${f} inserts a row whose id is needed`);
    }
  }
});
