// The current schema, expressed for both engines.
//
// Only a handful of things actually differ, so the tables are written once with small
// substitutions rather than as two divergent files that would drift apart:
//
//   auto-increment key   SQLite INTEGER PRIMARY KEY AUTOINCREMENT
//                        Postgres INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
//   floating point       SQLite REAL / Postgres DOUBLE PRECISION
//   case-insensitive     SQLite COLLATE NOCASE on the email column.
//   email                Postgres relies on the application always storing lower case
//                        (profile.js/login/oauth all lower-case before writing) plus a
//                        lower(email) unique index as a safety net.
//
// Booleans stay INTEGER 0/1 on both engines so application code never has to branch.
const SCHEMA_VERSION = 3;

const parts = (pg) => ({
  id: pg ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT',
  real: pg ? 'DOUBLE PRECISION' : 'REAL',
  email: pg ? 'TEXT NOT NULL UNIQUE' : 'TEXT NOT NULL UNIQUE COLLATE NOCASE',
});

function ddl(dialect) {
  const pg = dialect === 'postgres';
  const t = parts(pg);

  return `
CREATE TABLE IF NOT EXISTS users (
  id ${t.id},
  name TEXT NOT NULL,
  email ${t.email},
  password_hash TEXT,
  google_id TEXT UNIQUE,
  email_verified INTEGER NOT NULL DEFAULT 0,
  role TEXT NOT NULL CHECK (role IN ('DONOR','RECIPIENT','DRIVER')),
  phone TEXT,
  address TEXT,
  lat ${t.real},
  lng ${t.real},
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (password_hash IS NOT NULL OR google_id IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_users_role_loc ON users(role, lat, lng);
${pg ? 'CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users(lower(email));' : ''}

CREATE TABLE IF NOT EXISTS recipients (
  id ${t.id},
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
  organization_name TEXT NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  current_load INTEGER NOT NULL DEFAULT 0 CHECK (current_load >= 0),
  current_need TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (current_need IN ('LOW','MEDIUM','HIGH')),
  accepted_food_types TEXT NOT NULL DEFAULT '[]',
  is_available INTEGER NOT NULL DEFAULT 1,
  availability_note TEXT,
  is_verified INTEGER NOT NULL DEFAULT 0,
  verified_at TEXT,
  verification_note TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS donations (
  id ${t.id},
  donor_id INTEGER NOT NULL REFERENCES users(id),
  food_type TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  quantity ${t.real} NOT NULL CHECK (quantity > 0),
  unit TEXT NOT NULL,
  meals INTEGER NOT NULL,
  weight_kg ${t.real} NOT NULL,
  pickup_address TEXT NOT NULL,
  pickup_lat ${t.real} NOT NULL,
  pickup_lng ${t.real} NOT NULL,
  expiry_time TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'AVAILABLE'
    CHECK (status IN ('AVAILABLE','MATCHED','DRIVER_ASSIGNED','PICKED_UP','DELIVERED','EXPIRED','CANCELLED')),
  matched_recipient_id INTEGER REFERENCES recipients(id),
  match_score ${t.real},
  match_breakdown TEXT,
  match_failure_reason TEXT,
  recipient_accepted INTEGER NOT NULL DEFAULT 0,
  declined_recipients TEXT NOT NULL DEFAULT '[]',
  driver_id INTEGER REFERENCES users(id),
  expiry_warned INTEGER NOT NULL DEFAULT 0,
  pickup_reminder_sent INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  matched_at TEXT,
  picked_up_at TEXT,
  delivered_at TEXT,
  cancelled_at TEXT,
  cancel_reason TEXT
);
CREATE INDEX IF NOT EXISTS idx_donations_status ON donations(status);
CREATE INDEX IF NOT EXISTS idx_donations_donor ON donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_status_expiry ON donations(status, expiry_time);
CREATE INDEX IF NOT EXISTS idx_donations_recipient ON donations(matched_recipient_id);
CREATE INDEX IF NOT EXISTS idx_donations_driver ON donations(driver_id);
CREATE INDEX IF NOT EXISTS idx_donations_delivered ON donations(status, delivered_at);
CREATE INDEX IF NOT EXISTS idx_donations_pickup_geo ON donations(status, pickup_lat, pickup_lng);

CREATE TABLE IF NOT EXISTS deliveries (
  id ${t.id},
  donation_id INTEGER NOT NULL UNIQUE REFERENCES donations(id),
  driver_id INTEGER REFERENCES users(id),
  pickup_address TEXT NOT NULL,
  pickup_lat ${t.real} NOT NULL,
  pickup_lng ${t.real} NOT NULL,
  drop_address TEXT NOT NULL,
  drop_lat ${t.real} NOT NULL,
  drop_lng ${t.real} NOT NULL,
  distance_km ${t.real} NOT NULL,
  eta_minutes INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING','ASSIGNED','PICKED_UP','DELIVERED','CANCELLED')),
  pickup_time TEXT,
  delivery_time TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_deliveries_driver ON deliveries(driver_id, status);
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON deliveries(status);

CREATE TABLE IF NOT EXISTS donation_events (
  id ${t.id},
  donation_id INTEGER NOT NULL REFERENCES donations(id),
  from_status TEXT,
  to_status TEXT NOT NULL,
  actor_user_id INTEGER REFERENCES users(id),
  actor_role TEXT,
  note TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_donation ON donation_events(donation_id, id);

CREATE TABLE IF NOT EXISTS notifications (
  id ${t.id},
  user_id INTEGER NOT NULL REFERENCES users(id),
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  donation_id INTEGER,
  severity TEXT NOT NULL DEFAULT 'INFO',
  channels TEXT,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read);
`;
}

// Postgres has no PRAGMA user_version, so the schema version lives in a table.
const META_DDL = `
CREATE TABLE IF NOT EXISTS schema_meta (
  id INTEGER PRIMARY KEY,
  version INTEGER NOT NULL
);`;

module.exports = { ddl, META_DDL, SCHEMA_VERSION };
